version: '3'

services:
  api-rest:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      TOKEN_SECRET: ${TOKEN_SECRET}
      BCRYPT_SALT_ROUND: ${BCRYPT_SALT_ROUND}
    ports:
      - "${API_PORT}:3000"
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
